
    <div class="row">
        <div class="col-12 mb-4">
            <h1 class="text-center">Bem vindo ao Sistema de Agenda de Contatos</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-12 mb-4">
            <h2 class="text-center">Objetivo Deste Projeto</h2>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-4 order-md-1">
            <p>IMAGEM DO OBJETIVO</p>
        </div>
        <div class="col-md-8 order-md-12" >
            <p>O objetivo desde projeto é realizar um pequeno CRUD, simulando uma agenda de contatos telefônicos</p>
        </div>
    </div>

    <div class="row">
        <div class="col-12 mb-4">
            <h2 class="text-center">Tecnologias Utilizadas</h2>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12 col-md-8 order-last order-md-first" >
            <p>O Bootstrap é um kit de ferramentas de código aberto para desenvolvimento com HTML, CSS e JS. Crie rapidamente protótipos de suas ideias ou construa seu aplicativo inteiro com nossas variáveis ​​e mixins Sass, sistema de grade responsivo, extensos componentes pré-construídos e poderosos plugins construídos no jQuery.</p>
        </div>
        <div class="col-12 col-md-4 order-first order-md-last">
            <p>IMAGEM DO BOOTSTRAP</p>
        </div> 
    </div>

    <div class="row justify-content-center">
        <div class="col-12 col-md-8 order-last order-md-last" >
            <p>O Bootstrap é um kit de ferramentas de código aberto para desenvolvimento com HTML, CSS e JS. Crie rapidamente protótipos de suas ideias ou construa seu aplicativo inteiro com nossas variáveis ​​e mixins Sass, sistema de grade responsivo, extensos componentes pré-construídos e poderosos plugins construídos no jQuery.</p>
        </div>
        <div class="col-12 col-md-4 order-first order-md-first">
            <p>IMAGEM DO PHP</p>
        </div> 
    </div>      
