<?php echo $this->doctype() ?>
<html lang="pt-br" style="height: 100%">
<head>
    <?php 
        echo $this->headTitle();
        echo $this->headMeta();
        echo $this->headScript();
        echo $this->headLink(); 
    ?>
</head>
<body style="height: 87%;">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-5">
        <a class="navbar-brand" title="Pagina Inicial" href="<?php echo $this->baseUrl() ?>">Agenda de Telefônica</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown dropdown">
                <div class="btn-group">
                    <a href="<?php echo $this->baseUrl('contato') ?>" class="btn btn-link nav-link">Contatos</a>
                    <a href="#" class="btn btn-link nav-link dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="sr-only">Toggle Dropdown</span>
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" title="Criar Novo Contato" href="<?php echo $this->baseURL();?>/contato/novo">Novo Contato</a>
                    </div>
                </div>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container col-12 col-lg-10 mb-5" style="height: 100%">
        <?php echo $this->layout()->content; ?>
    </div>

    <footer class="navbar sticky-bottom navbar-dark bg-primary">
        <div class="container">
            <div class="navbar-text">
            <div class="row">
                <div class="col-lg-4">
                    <a href="#"> LINKEDIN</a>
                    <a href="#"> FACEBOOK</a>
                    <a href="#"> GITHUB</a>
                </div>
                <div class="col-md-4">
                    <a href="#"> LINKEDIN</a>
                    <a href="#"> FACEBOOK</a>
                    <a href="#"> GITHUB</a>
                </div>
                <div class="col-md-4">
                    <a href="#"> LINKEDIN</a>
                    <a href="#"> FACEBOOK</a>
                    <a href="#"> GITHUB</a>
                </div>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>