-- MySQL Script generated by MySQL Workbench
-- Sat Sep  8 21:21:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agenda_contatos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agenda_contatos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agenda_contatos` DEFAULT CHARACTER SET utf8 ;
USE `agenda_contatos` ;

-- -----------------------------------------------------
-- Table `agenda_contatos`.`Contatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda_contatos`.`Contatos` (
  `idContato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `organização` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `idUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idContato`))
ENGINE = InnoDB
COMMENT = 'tabela de contatos telefonicos';


-- -----------------------------------------------------
-- Table `agenda_contatos`.`Telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda_contatos`.`Telefones` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(14) NULL,
  `idContato` INT NOT NULL,
  PRIMARY KEY (`idTelefone`, `idContato`),
  INDEX `fk_Telefones_Contatos_idx` (`idContato` ASC) VISIBLE,
  CONSTRAINT `fk_Telefones_Contatos`
    FOREIGN KEY (`idContato`)
    REFERENCES `agenda_contatos`.`Contatos` (`idContato`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'tabela de numeros telefonicos'
KEY_BLOCK_SIZE = 4;


-- -----------------------------------------------------
-- Table `agenda_contatos`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda_contatos`.`Usuarios` (
  `idUsuario` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Tabela de usuarios';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
